name: TimingSystemRESTApi
version: 0.0.2-RC1
authors: [Justin Brubaker (JustBru00)]
softdepend: [TimingSystem]
main: com.frosthex.timingsystem.restapi.TimingSystemRESTApiPlugin
api-version: 1.19

commands:
  timingsystemrestapi: 
    description: Command for administrators to manage the timingsystemrestapi.